apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: certificate-watchdog
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      labels:
        job: certificate-watchdog
    spec:
      template:
        spec:
          containers:
          - name: certificate-watchdog
            image: perl
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          restartPolicy: OnFailure
